import math
import random

import numpy as np
import pytest
from testing_common import compare_pp

from skrample import scheduling
from skrample.sampling import functional, interface, models, structured

type SamplerTestKey = tuple[
    type[structured.StructuredSampler] | type[functional.FunctionalSampler],
    type[scheduling.ScheduleCommon],
    type[models.DiffusionModel],
]

MEASURED_SAMPLERS: list[structured.StructuredSampler | functional.FunctionalSampler] = [
    functional.RKUltra(),
    structured.Adams(),
    structured.SPC(),
]
MEASURED_SCHEDULES: list[scheduling.ScheduleCommon] = [scheduling.Linear(), scheduling.Scaled()]
MEASURED_MODELS: list[models.DiffusionModel] = [
    models.DataModel(),
    models.FlowModel(),
    # models.NoiseModel(),  # / zero
    models.VelocityModel(),
]

MEASURED_STEPS: int = 7
MEASURED_SEED: int = 42


def capture(
    sampler: functional.FunctionalSampler | structured.StructuredSampler,
    schedule: scheduling.ScheduleCommon,
    model: models.DiffusionModel,
) -> list[float]:
    samples: list[float] = []
    random.seed(MEASURED_SEED)
    (
        interface.StructuredFunctionalAdapter(sampler) if isinstance(sampler, structured.StructuredSampler) else sampler
    ).generate_model(
        lambda x, t, s: x - math.sin(t),
        model,
        scheduling.Hyper(schedule),
        lambda: random.random(),
        MEASURED_STEPS,
        callback=lambda x, i, t, s: samples.append(x),
    )
    return samples


# Auto generated by scripts/sampling_self_measure.py
# fmt: off
MEASURED_SAMPLER_RESULTS: dict[SamplerTestKey, list[float]] = {
    (functional.RKUltra, scheduling.Linear, models.DataModel): [0.5780598392186804, 0.47984288272550235, 0.36652751218728047, 0.44357997939897875, 0.6844909932628795, 0.45987338592721855, 0.5951793487736575],  # noqa: E501
    (functional.RKUltra, scheduling.Linear, models.FlowModel): [0.6541411854539834, 0.6575909905968154, 0.6158597768420465, 0.4742539272590272, 0.2790714207371206, 0.29258072035226296, 0.2630653895681999],  # noqa: E501
    (functional.RKUltra, scheduling.Linear, models.VelocityModel): [0.6124513781869325, 0.5500072845558036, 0.43877573589101987, 0.25002813549326974, 0.06398119136049375, 0.09509440076489664, 0.07264199451746078],  # noqa: E501
    (functional.RKUltra, scheduling.Scaled, models.DataModel): [0.6300931871907277, 0.6176224267634932, 0.6210501754229566, 0.8150691665877265, 1.103791875801471, 0.995328115543478, 1.130634078389917],  # noqa: E501
    (functional.RKUltra, scheduling.Scaled, models.FlowModel): [0.664132347336799, 0.708288578272592, 0.7392745926547724, 0.5874191175220908, 0.3507488804008957, 0.30995208778899164, 0.15800230361404097],  # noqa: E501
    (functional.RKUltra, scheduling.Scaled, models.VelocityModel): [0.6466992262396786, 0.647570542272716, 0.605409393836501, 0.3622010992613355, 0.11677787277282146, 0.16251186182339153, 0.0791635631891336],  # noqa: E501
    (structured.Adams, scheduling.Linear, models.DataModel): [0.5823892132380544, 0.45238300627281497, 0.3893269179260654, 0.22944591590064134, 1.0260936490800747, 0.47614703345685516, 0.6114529963032942],  # noqa: E501
    (structured.Adams, scheduling.Linear, models.FlowModel): [0.652357160411046, 0.6865655116121595, 0.5897498257234484, 0.5503720966982281, 0.12391546260993933, 0.25062205385363334, 0.2240010031899688],  # noqa: E501
    (structured.Adams, scheduling.Linear, models.VelocityModel): [0.6082499371443788, 0.5759467522266517, 0.3996314973648122, 0.34379120213634495, -0.09453883964299331, 0.10484655646602958, 0.08104875615666654],  # noqa: E501
    (structured.Adams, scheduling.Scaled, models.DataModel): [0.6313689484502868, 0.5963880658262994, 0.639788604742546, 0.6078314580200911, 1.390473704962506, 1.0096464267112562, 1.1449523895576952],  # noqa: E501
    (structured.Adams, scheduling.Scaled, models.FlowModel): [0.6634599890325708, 0.7290803151980236, 0.7161887251367887, 0.6899822151363814, 0.12091613842652106, 0.3321052690917803, 0.171353101758476],  # noqa: E501
    (structured.Adams, scheduling.Scaled, models.VelocityModel): [0.6453068566447652, 0.6685746457837283, 0.5608953018885953, 0.5153161547316122, -0.1860890876184754, 0.22329686513620867, 0.12198019090845079],  # noqa: E501
    (structured.SPC, scheduling.Linear, models.DataModel): [0.5823892132380544, 0.4586771307892887, 0.3741928361603825, 0.20446379350926672, 1.0037336805147574, 0.4694307383584173, 0.6047367012048563],  # noqa: E501
    (structured.SPC, scheduling.Linear, models.FlowModel): [0.652357160411046, 0.6839718628050788, 0.6135188719216544, 0.5811791631975856, 0.14133992123072664, 0.2635454619542076, 0.23603296343782088],  # noqa: E501
    (structured.SPC, scheduling.Linear, models.VelocityModel): [0.6082499371443788, 0.5698386190526368, 0.41648461030717204, 0.35170696362721426, -0.11333390686698243, 0.07326063755909841, 0.05382038742020298],  # noqa: E501
    (structured.SPC, scheduling.Scaled, models.DataModel): [0.6313689484502868, 0.5990537809889829, 0.6145638214778157, 0.5604015372368046, 1.3984895479002883, 0.9429774144798273, 1.0782833773262663],  # noqa: E501
    (structured.SPC, scheduling.Scaled, models.FlowModel): [0.6634599890325708, 0.7276754161913265, 0.7441508235578342, 0.7271492552656235, 0.10823100791576633, 0.3722253198512067, 0.19553178254985126],  # noqa: E501
    (structured.SPC, scheduling.Scaled, models.VelocityModel): [0.6453068566447652, 0.6656652764064962, 0.5865910687657327, 0.5294679004438534, -0.24635072058839225, 0.23832813302233824, 0.13256813474580895],  # noqa: E501
}
# fmt: on


@pytest.mark.parametrize(("key"), MEASURED_SAMPLER_RESULTS.keys())
def test_self_schedules(key: SamplerTestKey) -> None:
    smp, sch, md = key
    compare_pp(
        np.asarray(capture(smp(), sch(), md()), dtype=np.float64),
        np.asarray(MEASURED_SAMPLER_RESULTS[key], dtype=np.float64),
        1e-3,
    )
