import itertools
import math
import random

import numpy as np
import pytest
from testing_common import ALL_MODIFIERS_OPTION, ALL_SCHEDULES, compare_pp

from skrample.diffusers import SkrampleWrapperScheduler
from skrample.sampling.structured import DPM
from skrample.scheduling import (
    Beta,
    Exponential,
    FlowShift,
    Hyper,
    Karras,
    Linear,
    ScheduleCommon,
    ScheduleModifier,
    SigmoidCDF,
    SkrampleSchedule,
)

# Auto generated by scripts/scheduling_self_measure.py
# fmt: off
MEASURED_SCHEDULES_STEPS: int = 7
MEASURED_SCHEDULE_RESULTS: dict[SkrampleSchedule, list[list[float]]] = {
    SigmoidCDF(): [[1000.0, 1.0], [947.9583168651002, 0.9479583168651002], [784.5162980308221, 0.7845162980308221], [500.00001498872194, 0.5000000149887219], [215.4837367982649, 0.2154837367982649], [52.04172598851842, 0.052041725988518424], [0.0, 0.0]],  # noqa: E501
    Karras(Linear()): [[1000.0, 1.0], [640.0676228854967, 0.6400676228854967], [391.23724404615456, 0.39123724404615456], [223.32169300007047, 0.22332169300007046], [113.087697264913, 0.11308769726491301], [42.977874172757744, 0.042977874172757745], [-7.304098846218134e-15, -7.304098846218135e-18]],  # noqa: E501
    Beta(Linear()): [[1000.0, 1.0], [908.5132044499549, 0.9085132044499549], [724.5867092223766, 0.7245867092223766], [500.0000000000001, 0.5000000000000001], [275.4132907776235, 0.2754132907776235], [91.48679555004529, 0.09148679555004528], [0.0, 0.0]],  # noqa: E501
    Exponential(Linear()): [[1000.0, 1.0], [586.2760326346498, 0.5862760326346498], [335.16121038319875, 0.33516121038319874], [182.74399763155685, 0.18274399763155685], [90.23250613657405, 0.09023250613657405], [34.08152486537192, 0.034081524865371915], [7.304098846218134e-15, 7.304098846218135e-18]],  # noqa: E501
    Hyper(Linear()): [[1000.0, 1.0], [914.5217069182931, 0.9145217069182932], [747.2650736871641, 0.7472650736871641], [500.0, 0.5], [252.73492631283594, 0.25273492631283595], [85.47829308170682, 0.08547829308170682], [0.0, 0.0]],  # noqa: E501
    Hyper(Hyper(Linear())): [[1000.0, 1.0], [964.3559372812321, 0.964355937281232], [839.9247768122915, 0.8399247768122915], [500.0, 0.5], [160.0752231877084, 0.1600752231877084], [35.644062718768, 0.035644062718768], [0.0, 0.0]],  # noqa: E501
}
# fmt: on


def test_mu_set() -> None:
    mu = 1.2345
    a = SkrampleWrapperScheduler(DPM(), Hyper(FlowShift(Hyper(Linear()))))
    b = SkrampleWrapperScheduler(DPM(), Hyper(FlowShift(Hyper(Linear()), shift=math.exp(mu))))
    a.set_timesteps(123, mu=mu)
    assert a.schedule == b.schedule


# modifier shouldn't matter if done properly but why not
@pytest.mark.parametrize(("schedule", "modifier"), itertools.product(ALL_SCHEDULES, ALL_MODIFIERS_OPTION))
def test_sigmas_to_points(schedule: type[ScheduleCommon], modifier: type[ScheduleModifier] | None) -> None:
    schedule_object = modifier(schedule()) if modifier else schedule()
    points = schedule_object.points(np.linspace(1, 0, 123))
    points_inv = schedule_object.sigmas_to_points(points[:, 1])

    for _ in range(0, 99):
        points_inv = schedule_object.sigmas_to_points(points_inv[:, 1])

    compare_pp(points, points_inv, 0.1)


@pytest.mark.parametrize(("schedule", "modifier"), itertools.product(ALL_SCHEDULES, ALL_MODIFIERS_OPTION))
def test_continuously_variable(schedule: type[ScheduleCommon], modifier: type[ScheduleModifier] | None) -> None:
    schedule_object = modifier(schedule()) if modifier else schedule()
    t100: list[float] = [0, 1, *(random.random() for _ in range(98))]
    points_batch = schedule_object.points(t100)
    points_single = np.array([schedule_object.point(t) for t in t100], dtype=np.float64)
    assert points_batch.shape == points_single.shape
    # Converting np.float64 -> float -> np.float64 should be exact
    assert np.array_equal(points_batch, points_single)


@pytest.mark.parametrize(("schedule", "modifier"), itertools.product(ALL_SCHEDULES, ALL_MODIFIERS_OPTION))
def test_zero_point(schedule: type[ScheduleCommon], modifier: type[ScheduleModifier] | None) -> None:
    schedule_object = modifier(schedule()) if modifier else schedule()
    assert schedule_object.point(0) == (0, 0)


@pytest.mark.parametrize(("key"), MEASURED_SCHEDULE_RESULTS.keys())
def test_self_schedules(key: ScheduleCommon) -> None:
    compare_pp(
        key.points(np.linspace(1, 0, MEASURED_SCHEDULES_STEPS)),
        np.asarray(MEASURED_SCHEDULE_RESULTS[key], dtype=np.float64),
        0.0,  # TODO (beinsezii): this is not realistic, I'm certain the github actions will give a better idea
    )
