import itertools
import math
import random

import numpy as np
import pytest
from testing_common import ALL_MODIFIERS, ALL_MODIFIERS_OPTION, ALL_SCHEDULES, compare_pp

from skrample.diffusers import SkrampleWrapperScheduler
from skrample.sampling.structured import DPM
from skrample.scheduling import (
    Beta,
    Exponential,
    FlowShift,
    Hyper,
    Karras,
    Linear,
    Probit,
    Scaled,
    ScheduleCommon,
    ScheduleModifier,
    Sinner,
    SkrampleSchedule,
)

# Auto generated by scripts/scheduling_self_measure.py
# fmt: off
MEASURED_SCHEDULES_STEPS: int = 7
MEASURED_SCHEDULE_RESULTS: dict[SkrampleSchedule, list[list[float]]] = {
    Karras(Linear()): [[1000.0, 1.0], [640.0676228854967, 0.6400676228854967], [391.23724404615456, 0.39123724404615456], [223.32169300007047, 0.22332169300007046], [113.08769726491302, 0.11308769726491302], [42.97787417275775, 0.04297787417275775], [0.0, 0.0]],  # noqa: E501
    Beta(Linear()): [[1000.0, 1.0], [908.5132044499549, 0.9085132044499549], [724.5867092223766, 0.7245867092223766], [500.0000000000001, 0.5000000000000001], [275.4132907776235, 0.2754132907776235], [91.48679555004529, 0.09148679555004528], [0.0, 0.0]],  # noqa: E501
    Exponential(Linear()): [[1000.0, 1.0], [586.2760326346498, 0.5862760326346498], [335.16121038319875, 0.33516121038319874], [182.74399763155682, 0.18274399763155683], [90.23250613657403, 0.09023250613657403], [34.08152486537191, 0.03408152486537191], [0.0, 0.0]],  # noqa: E501
    Probit(Linear()): [[1000.0, 1.0], [947.9583168651002, 0.9479583168651002], [784.5162980308221, 0.7845162980308221], [500.00001498872194, 0.5000000149887219], [215.4837367982649, 0.2154837367982649], [52.04172598851842, 0.052041725988518424], [0.0, 0.0]],  # noqa: E501
    Hyper(Linear()): [[1000.0, 1.0], [914.5217069182931, 0.9145217069182932], [747.2650736871641, 0.7472650736871641], [500.0, 0.5], [252.73492631283594, 0.25273492631283595], [85.47829308170682, 0.08547829308170682], [0.0, 0.0]],  # noqa: E501
    Sinner(Linear()): [[1000.0, 1.0], [941.6266231083632, 0.9416266231083632], [831.9166561097303, 0.8319166561097303], [649.6057871357956, 0.6496057871357956], [415.9583280548651, 0.4159583280548651], [182.31086897393482, 0.1823108689739348], [-0.0, -0.0]],  # noqa: E501
    Hyper(Hyper(Linear())): [[1000.0, 1.0], [964.3559372812321, 0.964355937281232], [839.9247768122915, 0.8399247768122915], [500.0, 0.5], [160.0752231877084, 0.1600752231877084], [35.644062718768, 0.035644062718768], [0.0, 0.0]],  # noqa: E501
    Karras(Scaled()): [[1000.0, 14.60577640981563], [901.5920110754307, 8.371002715265938], [774.156996731441, 4.532454234225927], [598.7831210942937, 2.267633802189574], [353.88805163515883, 0.9974168381004495], [93.5682770444963, 0.3274801987781344], [0.0, 0.0]],  # noqa: E501
    Beta(Scaled()): [[1000.0, 14.60577640981563], [983.9977840790286, 13.269540729561156], [944.7543425336056, 10.583151464426125], [875.1710683960972, 7.302888204907817], [746.5141578253637, 4.022624945389506], [442.8229979972443, 1.336235680254477], [0.0, 0.0]],  # noqa: E501
    Exponential(Scaled()): [[1000.0, 14.60577640981563], [871.3325338119556, 7.162556750038259], [709.7218790105056, 3.4544742518414058], [498.7583673567279, 1.6071720839721488], [247.31604941814643, 0.6868782930238951], [51.989150253132415, 0.2284039424877292], [0.0, 0.0]],  # noqa: E501
    Probit(Scaled()): [[1000.0, 14.60577640981563], [991.1308744402521, 13.845667221956813], [958.7933293649952, 11.45846963889447], [875.1710743022625, 7.302888423829737], [686.3520666627805, 3.147307279627018], [274.9240126203694, 0.7601098137691914], [0.0, 0.0]],  # noqa: E501
    Hyper(Scaled()): [[1000.0, 14.60577640981563], [914.5217069182931, 8.966444294288356], [747.2650736871641, 4.03544418657589], [500.0, 1.6138389686076384], [252.73492631283594, 0.7009291355897483], [85.47829308170682, 0.30896870377454555], [0.0, 0.0]],  # noqa: E501
    Sinner(Scaled()): [[1000.0, 14.60577640981563], [941.6266231083632, 10.399664840949294], [831.9166561097303, 5.9042072609437914], [649.6057871357956, 2.73249754032781], [415.9583280548651, 1.2237197346340034], [182.31086897393482, 0.5282203858500616], [-0.0, 0.0]],  # noqa: E501
    Hyper(Hyper(Scaled())): [[1000.0, 14.60577640981563], [964.3559372812321, 11.830237593725956], [839.9247768122915, 6.13520437896842], [500.0, 1.6138389686076384], [160.0752231877084, 0.477115487396025], [35.644062718768, 0.18426081583294698], [0.0, 0.0]],  # noqa: E501
}
# fmt: on


def test_mu_set() -> None:
    mu = 1.2345
    a = SkrampleWrapperScheduler(DPM(), Hyper(FlowShift(Hyper(Linear()))))
    b = SkrampleWrapperScheduler(DPM(), Hyper(FlowShift(Hyper(Linear()), shift=math.exp(mu))))
    a.set_timesteps(123, mu=mu)
    assert a.schedule == b.schedule


# modifier shouldn't matter if done properly but why not
@pytest.mark.parametrize(("schedule", "modifier"), itertools.product(ALL_SCHEDULES, ALL_MODIFIERS_OPTION))
def test_sigmas_to_points(schedule: type[ScheduleCommon], modifier: type[ScheduleModifier] | None) -> None:
    schedule_object = modifier(schedule()) if modifier else schedule()
    points = schedule_object.points_np(np.linspace(1, 0, 33))
    points_inv = schedule_object._sigmas_to_points(points[:, 1], points[:, 2])

    for _ in range(0, 99):
        points_inv = schedule_object._sigmas_to_points(points_inv[:, 1], points_inv[:, 2])

    compare_pp(points, points_inv, 0.1)


@pytest.mark.parametrize(("schedule", "modifier"), itertools.product(ALL_SCHEDULES, ALL_MODIFIERS_OPTION))
def test_continuously_variable(schedule: type[ScheduleCommon], modifier: type[ScheduleModifier] | None) -> None:
    schedule_object = modifier(schedule()) if modifier else schedule()
    t100: list[float] = [0, 1, *(random.random() for _ in range(98))]
    points_batch = schedule_object.points_np(t100)
    points_single = np.array([schedule_object.point(t) for t in t100], dtype=np.float64)
    assert points_batch.shape == points_single.shape
    # Converting np.float64 -> float -> np.float64 should be exact
    assert np.array_equal(points_batch, points_single)


@pytest.mark.parametrize(("schedule", "modifier"), itertools.product(ALL_SCHEDULES, ALL_MODIFIERS_OPTION))
def test_zero_point(schedule: type[ScheduleCommon], modifier: type[ScheduleModifier] | None) -> None:
    schedule_object = modifier(schedule()) if modifier else schedule()
    assert schedule_object.point(0) == (0, 0, 1)


@pytest.mark.parametrize(("schedule", "modifier"), itertools.product(ALL_SCHEDULES, ALL_MODIFIERS))
def test_modified_one_point(schedule: type[ScheduleCommon], modifier: type[ScheduleModifier]) -> None:
    base = schedule()
    modified = modifier(base)
    np.testing.assert_allclose(modified.point(1), base.point(1), rtol=0, atol=1e-15)


@pytest.mark.parametrize(("key"), MEASURED_SCHEDULE_RESULTS.keys())
def test_self_schedules(key: ScheduleCommon) -> None:
    compare_pp(
        key.points_np(np.linspace(1, 0, MEASURED_SCHEDULES_STEPS))[:, :2],  # TODO (beinsezii): measure alphas
        np.asarray(MEASURED_SCHEDULE_RESULTS[key], dtype=np.float64),
        1e-3,
    )
