#! /usr/bin/env python

import itertools
import math
import random

from skrample import scheduling
from skrample.sampling import functional, interface, models, structured

type SamplerTestKey = tuple[
    type[structured.StructuredSampler] | type[functional.FunctionalSampler],
    type[scheduling.ScheduleCommon],
    type[models.DiffusionModel],
]

MEASURED_SAMPLERS: list[structured.StructuredSampler | functional.FunctionalSampler] = [
    functional.RKUltra(),
    structured.Adams(),
    structured.SPC(),
]
MEASURED_SCHEDULES: list[scheduling.ScheduleCommon] = [scheduling.Linear(), scheduling.Scaled()]
MEASURED_MODELS: list[models.DiffusionModel] = [
    models.DataModel(),
    models.FlowModel(),
    # models.NoiseModel(),  # / zero
    models.VelocityModel(),
]

MEASURED_STEPS: int = 7
MEASURED_SEED: int = 42


def capture(
    sampler: functional.FunctionalSampler | structured.StructuredSampler,
    schedule: scheduling.ScheduleCommon,
    model: models.DiffusionModel,
) -> list[float]:
    samples: list[float] = []
    random.seed(MEASURED_SEED)
    (
        interface.StructuredFunctionalAdapter(sampler) if isinstance(sampler, structured.StructuredSampler) else sampler
    ).generate_model(
        lambda x, t, s: x - math.sin(t),
        model,
        scheduling.Hyper(schedule),
        lambda: random.random(),
        MEASURED_STEPS,
        callback=lambda x, i, t, s: samples.append(x),
    )
    return samples


print("# Auto generated by scripts/sampling_self_measure.py")
print("# fmt: off")
print("MEASURED_SAMPLER_RESULTS: dict[SamplerTestKey, list[float]] = {")


for sampler, schedule, model in itertools.product(MEASURED_SAMPLERS, MEASURED_SCHEDULES, MEASURED_MODELS):
    label = type(sampler).__name__
    module = "structured" if isinstance(sampler, structured.StructuredSampler) else "functional"

    print(
        f"    ({module}.{label}, scheduling.{type(schedule).__name__}, models.{type(model).__name__}): "
        f"{capture(sampler, schedule, model)},  # noqa: E501"
    )
print("}")
print("# fmt: on")
