#! /usr/bin/env python


from collections.abc import Sequence

import numpy as np

from skrample.scheduling import (
    Beta,
    Exponential,
    Hyper,
    Karras,
    Linear,
    ScheduleModifier,
    Siggauss,
    SkrampleSchedule,
)

MEASURED_SCHEDULES: list[SkrampleSchedule] = [
    Karras(Linear()),
    Beta(Linear()),
    Exponential(Linear()),
    Siggauss(Linear()),
    Hyper(Linear()),
    Hyper(Hyper(Linear())),
    # Hyper(Linear(), tail=False),
    # Hyper(Linear(), scale=-2),
    # Hyper(Hyper(Linear(), scale=4), scale=-3),
]
STEPS: int = 7

print("# Auto generated by scripts/scheduling_self_measure.py")
print("# fmt: off")
print(f"MEASURED_SCHEDULES_STEPS: int = {STEPS}")
print("MEASURED_SCHEDULE_RESULTS: dict[SkrampleSchedule, list[list[float]]] = {")
for schedule in MEASURED_SCHEDULES:
    graph: Sequence[SkrampleSchedule] = schedule.all if isinstance(schedule, ScheduleModifier) else (schedule,)
    graph_string = "".join(type(g).__name__ + "(" for g in graph) + ")" * len(graph)
    print(f"    {graph_string}: {schedule.points(np.linspace(1, 0, STEPS)).tolist()},  # noqa: E501")
print("}")
print("# fmt: on")
