#! /usr/bin/env python


from collections.abc import Sequence

import numpy as np

from skrample.scheduling import (
    Beta,
    Exponential,
    Hyper,
    Karras,
    Linear,
    Probit,
    Scaled,
    ScheduleModifier,
    Sinner,
    SkrampleSchedule,
    SubSchedule,
)

MEASURED_SCHEDULES: list[SkrampleSchedule] = [
    Karras(Linear()),
    Beta(Linear()),
    Exponential(Linear()),
    Probit(Linear()),
    Hyper(Linear()),
    Sinner(Linear()),
    Hyper(Hyper(Linear())),
    Karras(Scaled()),
    Beta(Scaled()),
    Exponential(Scaled()),
    Probit(Scaled()),
    Hyper(Scaled()),
    Sinner(Scaled()),
    Hyper(Hyper(Scaled())),
]
STEPS: int = 7

print("# Auto generated by scripts/scheduling_self_measure.py")
print("# fmt: off")
print(f"MEASURED_SCHEDULES_STEPS: int = {STEPS}")
print("MEASURED_SCHEDULE_RESULTS: dict[SkrampleSchedule, list[list[float]]] = {")
for schedule in MEASURED_SCHEDULES:
    graph: Sequence[SkrampleSchedule] = (
        schedule.all if isinstance(schedule, ScheduleModifier | SubSchedule) else (schedule,)
    )
    graph_string = "".join(type(g).__name__ + "(" for g in graph) + ")" * len(graph)
    print(f"    {graph_string}: {schedule.points_np(np.linspace(1, 0, STEPS)).tolist()},  # noqa: E501")
print("}")
print("# fmt: on")
